dist: trusty
sudo: false
language: go
matrix:
  include:
  - go: 1.x
    env: LATEST=true
  - go: 1.13.x
  - go: tip
  allow_failures:
  - go: tip
before_install:
- go get github.com/mitchellh/gox
install:
- bash scripts/gogetcookie.sh
- go get github.com/mitchellh/gox
script:
- make test
- make vet
- if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -output="{{.OS}}/terraform-provider-flash"
  -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
- if [ "${LATEST}" = "true" ]; then sha1sum windows/terraform-provider-flash.exe
  terraform-provider-flash.windows.sha1; tar -czf terraform-provider-flash.windows.tar.gz  windows/terraform-provider-flash.exe;
  fi
- if [ "${LATEST}" = "true" ]; then sha1sum darwin/terraform-provider-flash
  terraform-provider-flash.darwin.sha1; tar -czf terraform-provider-flash.darwin.tar.gz  darwin/terraform-provider-flash;
  fi
- if [ "${LATEST}" = "true" ]; then sha1sum linux/terraform-provider-flash >
  terraform-provider-flash.linux.sha1; tar -czf terraform-provider-flash.linux.tar.gz  linux/terraform-provider-flash;
  fi
deploy:
  provider: releases
  api_key:
    secure: ZW5WPd6KuYqB+nnUl2O3s/jeEubnr+T3oQ6QQuZXgy4GYjIGjnzBeX0FqF42x7x6sj3/9fxP65AwVJgmRjlryqClfTDZjh6GwV6QKnIAhgXdGNOaJZuUJDBmHfcRrqUucvqoCtJiumnITejwpM/qtwd8sO1/RgGe+5cLEXSXpF0wh4ysxCW9hLIA03VvxLXKk+0mjRGyqerXd9XvISxnASbQkXLXCSldoXoN5rWlHLREGMRaVAL2eOP6DyUgGXw/OJIB4P8ic4CRO1EOu4bi+SIgaT3fny5XJhq8ova+jyyD3mFFRjn/qrJ7iarlalfMZ3oetL2LpZ9832fxU1NhXdK0sDvpUFFCwtD7wwAKv8N4OD5wLkbVtR5pT/2g34j6p7ZU/5kcYS8tnUM8lxSWZTAW3X24xX6Yu4P3GEAw7U3Z9ORQ4HaoWR37gysONBB6gDtJLjfk9CZdMebFfvGgQVVJfBRsHlIPf0BoOlUT2nOqOlMz+rHxdevtblsW0Uav2xJS4Bk4N0L24RF0ywbuoFMuSZ/zC/ZKbwVY+4Sk/PkVAHEA02rPLtiBWkI/5Q+Ao1B9DN/IoArqLsaVDjRQfx9BeJGSF41Ssw1OAEP9MLcmQKaAIf428DDt5JLTaiTJ0cqOhIyiMwUXoFw2PIyvpNlManoLzZwQjkA1U/XKY9Q=
  file:
  - terraform-provider-flash.linux.tar.gz
  - terraform-provider-flash.linux.sha1
  - terraform-provider-flash.darwin.tar.gz
  - terraform-provider-flash.darwin.sha1
  - terraform-provider-flash.windows.tar.gz
  - terraform-provider-flash.windows.sha1
  skip_cleanup: true
  on:
    repo: devans10/terraform-provider-flash
    tags: true
env:
  global:
  - secure: deAUzT04UaxVdT9byBvMp8fIWTEGImV/kULtfltCkfYY0urnoSLRq3n1QkoIBsNTl3jUw5FX3szgRpMberVAJlqP3Yk7yOktWS0lsg/RkLqc0YTRZ80Btp978vapzKYqNPe4IJ8BTZqaVQ0Es9eQL5WsKVgSEUcUyHNEETWtxhfRI/Ex1nHOuoUkgPvkDAi/0zs8w2pgVLqbPTbWMuXk7l8F9dbVtzf4fs9oxHsxi89vhHDNA88U+ZPajzKaABK698eXvayntL5tfCEz4l5A1vkic6KCqwkOAGFFg/ctMIXgDjixTLMpHCh8cjJYkQXv0NgPSkNQPEuvgIi1p7chFoxl2u8A/r5U/73UH0u8WiP5h31VwAfrizow8GczI+Lwu9jLsONca4UyWJPlsozC33aTDYCg7n3IqTdfHjr8TpQtzqVlMF53nANz9nNa6G/yyy6jKSh/qRZ0f6aNYZrVGuAkYWbZluadWJojtyG3vEliHqRWzP9O0gKHosdmEC9vsb3E8+oBe1GhILcpd7EZqFGhkuKlna8bNO37IIw35Z/bLmNyqoJ2PIM3SS4j8GfYIR2xyvcfd4/qcgVpt+y9r++CV9LJfvrzQ6qQ+gbr8jOJfL5WhJFEWlramyYgr5O8fdkA6fHtYZWngMhCt0XayNOlYNWko0yvwjzhv6X5J+c=
  - secure: ZW5WPd6KuYqB+nnUl2O3s/jeEubnr+T3oQ6QQuZXgy4GYjIGjnzBeX0FqF42x7x6sj3/9fxP65AwVJgmRjlryqClfTDZjh6GwV6QKnIAhgXdGNOaJZuUJDBmHfcRrqUucvqoCtJiumnITejwpM/qtwd8sO1/RgGe+5cLEXSXpF0wh4ysxCW9hLIA03VvxLXKk+0mjRGyqerXd9XvISxnASbQkXLXCSldoXoN5rWlHLREGMRaVAL2eOP6DyUgGXw/OJIB4P8ic4CRO1EOu4bi+SIgaT3fny5XJhq8ova+jyyD3mFFRjn/qrJ7iarlalfMZ3oetL2LpZ9832fxU1NhXdK0sDvpUFFCwtD7wwAKv8N4OD5wLkbVtR5pT/2g34j6p7ZU/5kcYS8tnUM8lxSWZTAW3X24xX6Yu4P3GEAw7U3Z9ORQ4HaoWR37gysONBB6gDtJLjfk9CZdMebFfvGgQVVJfBRsHlIPf0BoOlUT2nOqOlMz+rHxdevtblsW0Uav2xJS4Bk4N0L24RF0ywbuoFMuSZ/zC/ZKbwVY+4Sk/PkVAHEA02rPLtiBWkI/5Q+Ao1B9DN/IoArqLsaVDjRQfx9BeJGSF41Ssw1OAEP9MLcmQKaAIf428DDt5JLTaiTJ0cqOhIyiMwUXoFw2PIyvpNlManoLzZwQjkA1U/XKY9Q=
